@extends('layouts.app')

@section('content')

<main role="main">
<div class="jumbotron">
  <div class="container">
    <h2 class="display-3">Conditions D'utilisation</h2>
    <br/>
    <p>
    Conditions Générales d’Utilisation du site AtypikHouse.com<br/>
Dernière mise à jour : 22 août 2018<br/>
<br/><br/>1. Introduction<br/>
<br/>
1.1 Le Groupe AtypikHouse (tel que défini ci-dessous) fournit une plateforme en ligne ainsi que différents outils, services et fonctions qui permettent aux propriétaires de référencer des biens immobiliers et aux vacanciers de réserver ces mêmes biens immobiliers (ensemble, les « Services »). Les Services sont fournis via des URL spécifiques à chaque pays via https://www.atypikhouse.com/  et également par le biais d’applications mobiles (sur téléphones portables, tablettes et autres appareils, quelle que soit leur interface) (collectivement, le « Site »). Les activités d’AtypikHouse en Europe sont gérées par la société AtypikHouse 29, rue Napoléon, 60350 Pierrefonds, France (« AtypikHouse », « nous », « nos », « notre »). 
<br/>1.2 Les présentes conditions générales d’utilisation (les « Conditions Générales d’Utilisation Vacanciers »), ainsi que notre Politique de confidentialité, régissent la relation entre AtypikHouse et toute partie consultant ou utilisant le Site ou un quelconque contenu ou service proposé sur le Site, en qualité de vacancier ou vacancier potentiel (le « Vacancier » ou « vous ») et non en qualité de propriétaire ou gérant de biens immobiliers. Le terme Vacancier désigne toute personne utilisant le Site pour obtenir des informations sur des locations de vacances ou pour réserver une location de vacances, que ce soit à des fins personnelles ou professionnelles, auprès de propriétaires ou gérants de biens immobiliers. Les réservations des locations de vacances sont soumises aux présentes Conditions Générales d’Utilisation Vacanciers.
<br/>1.3 Les Conditions Générales d’Utilisation Vacanciers constituent un contrat juridiquement contraignant entre AtypikHouse et le Vacancier. En consultant ou utilisant le Site ou les plateformes ou systèmes de AtypikHouse, vous reconnaissez que vous acceptez les Conditions Générales d’Utilisation Vacanciers et notre Politique de confidentialité et convenez de vous y soumettre, en votre nom et au nom de toute personne mentionnée dans votre réservation. Toute réservation ou utilisation effectuée par un Vacancier par le biais d’un site AtypikHouse est régie par les conditions générales du site AtypikHouse sur lequel la réservation est réalisée (et non pas nécessairement celles du site AtypikHouse sur lequel la Location de vacances était initialement référencée). En cas de quelconques contradictions entre les conditions générales du site AtypikHouse sur lequel vous avez trouvé la Location de vacances et les conditions générales du site AtypikHouse sur lequel vous avez réalisé la réservation, les conditions générales du site AtypikHouse sur lequel vous avez réalisé la réservation prévaudront. Si vous n’approuvez pas pleinement les Conditions Générales d’Utilisation Vacanciers, vous n’êtes pas autorisé(e) à consulter ou utiliser le Site.
<br/>1.4 AtypikHouse n’autorise aucune personne à s’enregistrer sur le Site à moins qu’elle n’ait  la capacité juridique nécessaire pour conclure des contrats juridiquement contraignants.
<br/>1.5 AtypikHouse est susceptible de modifier les présentes Conditions Générales d’Utilisation Vacanciers de temps en temps pour des raisons telles que des changements d’activité commerciale, l’introduction, la modification ou l’arrêt de produits ou outils, ou lors de nouveautés législatives. Vous serez informé en tenant compte d’un préavis d’une durée raisonnable des changements des Conditions Générales d’Utilisation Vacanciers ou de notre décision d’y mettre fin. Nous vous informerons de tels changements au travers du Site ou par email. Veuillez visiter cette page périodiquement afin de prendre connaissance de la version la plus récente des Conditions Générales d’Utilisation Vacanciers.
<br/><br/>2. Généralités
<br/>
<br/>2.1 Le présent Site est une plateforme où les Vacanciers peuvent consulter des annonces de location de vacances (les « Locations de vacances ») proposées par d’autres personnes, y compris des propriétaires, locataires ou gérants de biens immobiliers (ci-après chacun d’eux un « Propriétaire » et, collectivement avec un Vacancier, les « Utilisateurs »), ou obtenir des informations sur ces Locations de vacances. Nous pourrions également proposer d'autres outils ou services permettant aux Utilisateurs de communiquer et de conclure des contrats de location ou d'autres transactions entre eux.
<br/>2.2 Le Site se définit uniquement comme un espace permettant aux Utilisateurs d’échanger entre eux, et AtypikHouse n'est pas et ne deviendra pas partie aux relations contractuelles entre le Vacancier et le Propriétaire. De plus, AtypikHouse ne peut en aucun cas intervenir en qualité de médiateur entre le Vacancier et le Propriétaire en cas d’un quelconque différend entre eux. Vous reconnaissez et convenez que le Vacancier et le Propriétaire sont responsables de remplir leurs obligations en vertu de tels contrats, et que AtypikHouse n'est aucunement partie à de tels contrats et rejette toute responsabilité résultant de ces contrats ou relative à ceux-ci. Cela s’appliquera même si le Site facilite la réservation d'une Location de vacances ou l'utilisation d'autres outils, services ou produits étant donné que AtypikHouse n’est partie à aucun contrat de location ou autre entre un Vacancier et Propriétaire.
<br/>2.3 Les Vacanciers conviennent qu’ils sont responsables de se conformer à toutes les lois, règles et réglementations applicables à leur utilisation du Site et de tous outils, produits ou services proposés sur le Site, ainsi qu’à toute transaction qu’ils effectuent sur le Site ou associée à leur utilisation du Site, et ils conviennent de s’y conformer. Les Vacanciers sont informés que les Propriétaires sont responsables de se conformer à toutes les lois, règles et règlementations applicables à leur annonce, à leur Location de vacances et à l'exercice de leurs activités de location, et qu’ils acceptent de s’y conformer. Veuillez noter que, même si  AtypikHouse n’est partie à aucune transaction de location et décline toute responsabilité pour la conformité à toutes lois ou réglementations applicables à une quelconque Location de vacances référencée sur le Site, il peut exister des circonstances dans lesquelles AtypikHouse pourrait être tenu (selon ce que nous déterminerons à notre seule et entière discrétion) de fournir des informations concernant une quelconque Annonce, ce afin de nous conformer aux demandes d’organismes publics ou réglementaires dans le cadre de quelconques procédures d’enquête, de litige ou administratives, et nous serons par ailleurs en droit de nous conformer à de telles obligations ou de les rejeter à notre seule et entière discrétion.
<br/>2.4 Des frais de service sont facturés par AtypikHouse au Vacancier qui réserve en ligne une Location de vacances sur le Site. Les frais de service couvrent l’utilisation du Site et des fonctionnalités telles que le service d’assistance 24h/24 et 7j/7. Les frais de service correspondent à un pourcentage du montant total de la location (ce montant total peut inclure des frais additionnels, – et un dépôt de garantie, facturés par le Propriétaire). Le Vacancier reconnaît et accepte expressément que le droit de rétractation est exclu en application de l’article L.221-28, 12° du Code de la consommation. En fonction du droit applicable dans le pays de résidence du Vacancier et/ou du Propriétaire, une TVA, une taxe de séjour (telles que définies au paragraphe 2.7) ou toutes autres taxes indirectes équivalentes applicables pourraient être ajoutées aux Frais de service (ou incluses à ces derniers). Le Propriétaire s’engage à ne pas encourager ni conseiller le Vacancier à contourner ou éviter le paiement des frais de service facturés par AtypikHouse, et le Vacancier s’engage à ne pas contourner ou éviter le paiement des frais de service.
<br/>2.5 AtypikHouse pourrait être dans l’obligation de collecter et de reverser des taxes (y compris la TVA, des taxes à la consommation et d’autres taxes équivalentes) sur les Frais de Service. Le cas échéant, AtypikHouse enverra au Vacancier une facture indiquant le montant des taxes facturées sur ces Frais de Service. Si le Vacancier est en droit de bénéficier d’une exonération de toutes taxes indirectes, ou de leur équivalent, sur les Frais de service, il doit fournir à  AtypikHouse les justificatifs d’une telle exonération.
<br/>2.6 Si le Vacancier est un voyageur d'affaires assujetti à la TVA ou un employé d'une entreprise qui remboursera la TVA facturée, il doit communiquer à AtypikHouse un numéro de TVA valide et son adresse de facturation associée afin que AtypikHouse applique un mécanisme d’auto-liquidation (« reverse charge ») de la TVA, le cas échéant, concernant les Frais de service. Si le Vacancier a une adresse de facturation au Royaume-Uni, la procédure de « reverse charge » ne sera pas applicable et la TVA britannique s'appliquera.
<br/>2.7 Collecte et reversement de la Taxe de séjour : les Vacanciers sont responsables du paiement de la Taxe de séjour (taxe de tourisme, taxe d'hébergement, ou autres taxes similaires requises par la juridiction locale), laquelle doit être généralement collectée par le Propriétaire. Dans certaines juridictions, AtypikHouse pourrait décider, à son entière discrétion, de collecter directement et de reverser la Taxe de séjour pour le compte des Propriétaires. Dans ce cas, les Propriétaires n’auront pas d’action à prendre pour collecter cette taxe auprès des Vacanciers ni pour la reverser à la commune locale. Dans les juridictions dans lesquelles une telle procédure de collecte sera mise en œuvre, le Propriétaire mandate et autorise par la présente AtypikHouse à collecter pour son compte la Taxe de séjour auprès des Vacanciers et à procéder aux déclarations nécessaires auprès de la commune locale, y compris le reversement de ladite taxe.
<br/>2.8 Le Site est constitué d’Annonces de Location de vacances fournies par des Propriétaires et de contenus fournis par d’autres parties. Ces contenus relèvent de la responsabilité du Propriétaire ou du tiers ayant créé lesdits contenus. Nous ne pouvons en aucun cas être tenus responsables de tels contenus étant donné que notre service consiste uniquement à vous fournir un accès à ces contenus et que notre rôle consiste simplement à vous fournir les moyens de communiquer directement avec le Propriétaire pour obtenir des informations sur une Location de vacances et de la réserver directement auprès du Propriétaire. Toutes les réservations que vous effectuez sont faites par vos soins directement auprès du Propriétaire, et votre contrat de location sera conclu entre le Propriétaire et vous. Ce contrat régira votre droit à occuper et utiliser la Location de vacances et pourrait contenir des obligations de payer des frais et taxes supplémentaires. AtypikHouse ne sera aucunement partie au contrat de location et AtypikHouse n’a aucune responsabilité envers vous pour la mise à disposition de la location par le Propriétaire. Nous n’approuvons, ne soutenons ni ne garantissons d’aucune manière l’authenticité, l’exactitude ou la fiabilité des informations contenues dans les Annonces du Site, ni des divers contenus ou opinions affichés par des tiers.
<br/><br/>3. Annonces de Location de vacances et interaction avec un Propriétaire
<br/>
<br/>3.1 Les Vacanciers sont informés que les Propriétaires sont intégralement responsables de l’ensemble des informations, notamment toutes images et tous textes et autres contenus, relatives aux Locations de vacances qu’ils proposent (les « Annonces »), ainsi que de les mettre à jour et de vérifier (le cas échéant) qu’elles sont correctement traduites. Par conséquent, lorsqu’une Annonce est reliée à un système de traduction automatique tel que Google Translate, il appartient au Propriétaire de vérifier que la traduction en résultant est exacte et de corriger toutes les erreurs éventuelles.
<br/>3.2 Si un Vacancier est intéressé par une Location de vacances, il peut envoyer une demande d’informations (une « Demande d’informations ») au Propriétaire sans avoir à s’enregistrer sur le Site, en indiquant son nom et toute information demandée. Nous et le Groupe AtypikHouse sommes susceptibles de vous envoyer de temps à autre des lettres d’information par email destinées à vous présenter les services que nous et le Groupe AtypikHouse proposons. Les Vacanciers peuvent choisir soit de recevoir nos lettres d’information lorsqu’ils soumettent une Demande d’informations soit demander à ne pas les recevoir au moment d’effectuer une réservation sur le Site, et peuvent à tout moment annuler leur abonnement à ces newsletters via le Centre des préférences de communication ou bien en cliquant sur le lien de désinscription qui figure en bas de la newsletter. Toutes modifications de vos préférences de Vacancier peuvent prendre quelques instants avant de prendre effet.  Pour plus d’informations concernant la collecte et le traitement de vos données personnelles, veuillez consulter notre Politique de données personnelles.
<br/>3.3 Le Vacancier recevra une confirmation de AtypikHouse une fois sa Demande d’informations envoyée au Propriétaire.
<br/>3.4 Le Propriétaire peut alors communiquer directement avec le Vacancier concernant sa Demande d’informations, et le Vacancier et le Propriétaire peuvent également communiquer entre eux via le Site (et via d’autres outils sur la plateforme AtypikHouse).
<br/>3.5 Le service de réservation en ligne, s'il a été autorisé par le Propriétaire, permet au Vacancier d’effectuer sa réservation en ligne, laquelle réservation doit être acceptée ou refusée par le Propriétaire dans un délai de 24 heures. Pour les paiements en ligne, le Vacancier dont la réservation a été confirmée par le Propriétaire peut régler le montant de sa réservation au travers de la passerelle de paiement par carte bancaire via le prestataire de paiement tiers et/ou AtypikHouse Payments. Le service de paiement en ligne est soumis aux conditions générales du prestataire de paiement tiers, ou dans le cas d’AtypikHouse Payments, aux termes de la Convention d’encaissement des frais de séjour, et le Vacancier reconnait et accepte que (à l’exception des obligations d’AtypikHouse Payments en vertu de la Convention d’encaissement des frais de séjour)   AtypikHouse n'exerce aucun contrôle sur le service et n’en est aucunement responsable.
<br/>3.6 Les communications entre Vacanciers et Propriétaires par le biais de la plateforme AtypikHouse ne doivent inclure aucune adresse électronique ni aucun numéro de téléphone. Veuillez noter que toute communication sur le Site (ou via la plateforme AtypikHouse) est accessible aux employés et représentants de AtypikHouse. Nous vous rappelons également que, conformément à nos exigences en matière de sécurité et de protection des comptes, nous sommes en droit de retirer ou d’expurger de quelconques informations au sein de ces communications (adresses électroniques ou numéros de téléphone, par exemple, ainsi que tout autre contenu que nous jugeons inapproprié ou non conforme aux lois et réglementations applicables).
<br/>3.7 AtypikHouse pourrait également utiliser ponctuellement des serveurs de messagerie électronique tiers pour envoyer des emails de Demandes d’informations, déterminer si celles-ci ont été reçues et analyser l’utilisation qui est faite de la fonction Demande d’informations fourni par ces systèmes de suivi tiers. Notre système ne conserve pas les messages indéfiniment, et par conséquent ils pourraient ne plus être accessibles une fois que le message vous a été remis.
Veuillez imprimer une copie de tout message important pour vous (reçus de paiement et confirmations de réservation, par exemple) afin de les archiver.
<br/>3.8 AtypikHouse décline toute responsabilité ou implication dans les communications entre le Propriétaire et le Vacancier.
<br/><br/>4. Positionnement et affichage dans les Résultats de Recherche
<br/>
<br/>AtypikHouse ne peut pas garantir qu’une Annonce apparaîtra dans un ordre spécifique dans les résultats de recherche sur le Site. L’ordre de recherche varie automatiquement selon les filtres de recherche utilisés par les Vacanciers, les préférences du Vacancier, ainsi que le classement par défaut de la propriété qui est déterminé par les caractéristiques de la propriété, la qualité de l’expérience, les frais de service payés par le Vacancier. Les caractéristiques de la propriété sont évaluées selon plusieurs critères, tels que les retours des Vacanciers, les commodités offertes, et la situation géographique de la propriété. La qualité de l’expérience est basée sur plusieurs critères tels que l’exactitude du calendrier de l’annonce, les délais de réponse du Propriétaire, le taux d’acceptation des réservations, la possibilité de réservation et de paiement en ligne, la cohérence des prix et l’expérience de qualité du séjour, ainsi que tous les autres facteurs que AtypikHouse peut à tout moment juger importants pour satisfaire ses utilisateurs. Les frais de services versés par le Vacancier pour les réservations sont également un facteur de positionnement relatif aux propriétés ayant des offres similaires, en fonction des critères de pertinence décrits ci-dessus. Si le Propriétaire a choisi la formule Annonces par Abonnement, les résultats de recherche pourraient également varier en fonction des critères de recherche utilisés par un Vacancier particulier. AtypikHouse se réserve le droit d’employer automatiquement différents algorithmes de recherche ou d’utiliser différentes méthodes pour optimiser les résultats du classement par défaut et maximiser la satisfaction des Vacanciers et des internautes en général. Il est possible que des Annonces en Formule à la commission, placées sur la base d’un non-abonnement, n’apparaissent pas toujours dans les résultats de recherche. Nous n’offrons aucune garantie que les Annonces distribuées sur des sites tiers s’afficheront ou s’afficheront selon un classement particulier. Les résultats de recherche et leur classement pourraient s’afficher dans un ordre différent sur l’application mobile de AtypikHouse et sur son Site internet. Afin d’optimiser l’expérience de recherche, tant pour les Propriétaires que pour les Vacanciers, et d’améliorer le classement par défaut, AtypikHouse se réserve le droit d‘effectuer occasionnellement des tests qui seront de durée limitée mais pourraient modifier la manière dont les Annonces sont affichées, ainsi que les résultats de recherche.
<br/><br/>5. Enregistrement et création de Compte
<br/><br/>
5.1 Si le Vacancier souhaite utiliser les autres services, hors Demandes d’informations, proposés sur le Site, il doit s’enregistrer auprès du Site. Un tel enregistrement est réservé aux personnes habilitées à conclure un contrat. A la fin de cette procédure d’enregistrement, un compte d’utilisateur pour le Site (un « Compte ») sera créé.
<br/>5.2 Pour obtenir un Compte, le Vacancier doit suivre les instructions de AtypikHouse pendant la procédure d’enregistrement. Vous pouvez ouvrir un Compte à l’aide d’une adresse électronique personnelle, ou en saisissant vos données de connexion à Facebook en cliquant sur le bouton de connexion avec Facebook sur l’écran d’enregistrement.
<br/>5.3 Le Compte du Vacancier inclut des informations accessibles publiquement à d'autres Utilisateurs du Site, et qui pourraient également être vues par des internautes qui ne sont pas enregistrés sur le Site, par exemple ces informations pourraient s’afficher dans les résultats de recherche d’un moteur de recherche tel que Google. Un Compte comprend, entre autres :
    <br/>Une page dédiée, appelée « Mon Profil », sur laquelle le nom de profil du Vacancier est un champ à remplir obligatoirement. Les autres informations personnelles et de voyage sont facultatives et fournies à la discrétion du Vacancier ;
    <br/>La possibilité de conserver un œil sur certaines Locations de vacances ;
    <br/>La possibilité d’enregistrer des commentaires concernant des Locations de vacances ;
    <br/>La possibilité de soumettre des appréciations au sujet des Locations de vacances dans lesquelles vous avez séjourné ;
    <br/>Un lien au compte Facebook du Vacancier. Si le Vacancier se connecte au Site par le biais de son compte Facebook ou lie son Compte à son compte Facebook, le Vacancier est informé et accepte de transférer ses données de connexion à Facebook et que la liste de ses amis Facebook ayant également un Compte s’affichera sur le Site. De telles informations seront affichées sur la page du profil du Vacancier ;
    <br/>La possibilité de partager avec d’autres personnes, tels que vos amis, des membres de votre famille ou vos contacts sur les réseaux sociaux, vos Locations de vacances préférées vos listes ;
    <br/>Un lien vers Appréciations du Propriétaire (telles que définies ci-après).
    <br/>5.4 La réglementation fiscale pourrait nous imposer de collecter des informations fiscales auprès des Vacanciers. Le Vacancier est responsable de vérifier que toutes les informations qu’il nous fournit sont exactes, complètes et à jour.
    <br/>5.5 Le Vacancier peut désactiver son Compte à tout moment et également désactiver le lien entre son Compte et sa page publique de Facebook à tout moment, en allant directement sur la page des paramètres de son profil. Le Vacancier reconnaît et accepte que, même s’il désactive son Compte, le Groupe AtypikHouse pourrait conserver certaines données en conformité aux dispositions de notre Politique de confidentialité et la Notice relative aux cookies. Le Vacancier reconnaît et accepte l’utilisation de ses données tel qu’indiqué dans la Politique de confidentialité et la Notice relative aux cookies. Le Vacancier reconnaît et accepte également que les données relatives séjours réservés via le Site que vous avez accepté de rendre publiques via le Groupe AtypikHouse pourraient être transmises et rester sur d’autres sites, par exemple Google dans l’hypothèse où les moteurs de recherche de Google copient le contenu de sites ou systèmes du Groupe AtypikHouse
    <br/>5.6 AtypikHouse utilise également Google Analytics pour obtenir des statistiques sur l’utilisation du Site. Ceci est expliqué de manière détaillée dans la Politique de confidentialité et la Notice relative aux cookies, ainsi que dans la politique de confidentialité de Google. Google pourrait agréger des données qu’il collecte au travers de ses différents services, y compris Google Analytics, Google Traduction, Google Maps et YouTube. Les Vacanciers reconnaissent et acceptent que le Groupe AtypikHouse ne maîtrise pas les collectes de données effectuées par Google.
    <br/><br/>6. Droits et obligations de AtypikHouse<br/>
    <br/>6.1 AtypikHouse fera tout son possible pour que toutes photographies fournies par le Propriétaire s’affichent sur le Site d’une manière aussi fidèle que possible à l’original. Le Vacancier reconnaît toutefois que les photos, telles qu’affichées dans les Annonces, pourraient différer légèrement des images originales s’il s’agit d’images non-numériques numérisées, ou en raison de différences de réglage des écrans employés pour les visualiser, et que AtypikHouse décline toute responsabilité concernant de telles différences.
    <br/>6.2 De plus, vous reconnaissez que le Propriétaire et non AtypikHouse est responsable de l’exactitude avec laquelle les images et descriptifs fournis représentent la Location de vacances en question.
    <br/>6.3 AtypikHouse pourrait occasionnellement procéder à une mise à niveau et une maintenance du Site, de ses plateformes et de ses systèmes, lesquelles sont susceptibles de limiter l’accès au Site. Dans la mesure du possible, AtypikHouse réalisera une telle maintenance à un moment où celle-ci affectera le moins possible les Vacanciers.
    <br/>6.4 Il est difficile d’identifier un Utilisateur sur Internet, et AtypikHouse ne peut assumer et décline l’entière responsabilité de vérifier la prétendue identité de chaque utilisateur. AtypikHouse recommande aux Vacanciers et aux Propriétaires d'échanger directement en utilisant les outils disponibles sur le Site, même si cela ne permet aucunement de vérifier l'identité des personnes avec lesquelles ils échangent. AtypikHouse recommande également aux Vacanciers de prendre toutes autres mesures raisonnables pour vérifier l'identité de tous Propriétaires et de vérifier les informations publiées sur le Site par tout Propriétaire concernant une Location de vacances, ainsi que le détail d'une réservation confirmée ou proposée. Le Vacancier convient (i) de protéger la confidentialité de ses données de connexion au Site (identifiant et mot de passe) et à son compte de messagerie (identifiant et mot de passe) et de ne les divulguer qu’à des tiers autorisés, (ii) d’instruire adéquatement toute personne à laquelle le Vacancier confie ses identifiant et mot de passe afin que ladite personne ne les divulgue à aucun tiers non autorisés, (iii) de nous contacter immédiatement et de sélectionner un nouvel identifiant et un nouveau mot de passe en ligne si le Vacancier pense qu’un tiers non autorisé a pris connaissance du mot de passe de son compte ou de son compte de messagerie auprès de AtypikHouse, et (iv) d’informer immédiatement AtypikHouse si le Vacancier est contacté par un quelconque tiers demandant de lui communiquer son identifiant et son mot de passe. En outre, si AtypikHouse suspecte qu’un tiers non autorisé a accès au compte du Vacancier, le Vacancier convient, sur simple demande de AtypikHouse, de changer sans délai son identifiant et son mot de passe et de prendre toutes autres mesures requises par AtypikHouse à cet égard. AtypikHouse déconseille vivement au Vacancier de communiquer à qui que ce soit son identifiant et son mot de passe concernant son compte ou sa messagerie personnelle. Toutefois, si le Vacancier communique son identifiant et son mot de passe ou manque à ses obligations de protection de ces informations de manière sécurisée, le Vacancier sera responsable de toute transaction effectuée par un tiers utilisant son identifiant et son mot de passe, de son compte ou de sa messagerie personnelle, même si cette transaction est frauduleuse et/ou si le Vacancier ne cherchait pas à la réaliser ou à ce qu’elle soit exécutée, et AtypikHouse ne pourra en aucun cas être tenu responsable envers vous dans une telle hypothèse ;
    <br/>6.5 Le Vacancier reconnaît que AtypikHouse n'est pas responsable de vérifier l'identité ou les actes des Propriétaires, ni d'établir la nature, condition ou existence d'une Location de vacances.
    <br/>6.6 AtypikHouse se réserve le droit de transférer les présentes Conditions Générales d’Utilisation Vacanciers et de céder ou sous-traiter à un tiers ou à toute autre entité appartenant au Groupe AtypikHouse tout ou partie de ses droits et obligations aux termes des présentes Conditions Générales d’Utilisation Vacanciers, mais ne le fera en aucun cas d’une façon limitant de quelconques garanties fournies au Vacancier aux termes des présentes Conditions Générales d’Utilisation Vacanciers.
    <br/><br/>7. Propriété intellectuelle
    <br/>
    <br/>7.1 Tout contenu apparaissant sur le Site est protégé par les droits d’auteur et les droits relatifs aux bases de données. Toute reproduction partielle ou totale du Site, y compris toute copie de textes, d’éléments visuels ou de designs, est interdite.
    <br/>7.2 Les Vacanciers sont en droit de télécharger, d’afficher et d’imprimer certaines pages du Site pour justifier de leur contrat avec AtypikHouse et de conserver une copie de leurs réservations. La mention « © 2018 AtypikHouse - tous droits réservés » doit clairement figurer dans le fichier en question ou sur l’impression concernée.
    <br/>7.3 Lorsqu’il publie ou transmet des contenus, de quelque nature que ce soit, y compris textes et images, par l’intermédiaire du Site (ou de la plateforme ou des systèmes AtypikHouse), le Vacancier déclare en détenir les droits nécessaires.   
    <br/>7.4 Si des marques déposées ou d’autres noms de propriétaires et autres marques figurent dans les Appréciations du Vacancier ou dans d’autres contenus qu’il publie, le Vacancier déclare en détenir les droits nécessaires.
    <br/>7.5 En publiant tout type de contenu sur le Site (y compris, sans s’y limiter, tous textes, descriptions, avis, photographies et autres), le Vacancier concède à Expedia, Inc., AtypikHouse et à chacune de leurs filiales ou sociétés affiliées un droit non exclusif, gratuit, cessible, irrévocable et pouvant être entièrement concédé en licence (à plusieurs niveaux) d’utiliser, reproduire, traduire, diffuser ou publier ces contenus et de les afficher ou produire en public, dans le monde entier, quel que soit le média utilisé, qu’il soit connu aujourd’hui ou inventé ultérieurement pour quelque usage que ce soit.
    <br/><br/>8. Compte, communications et Appréciations du Vacancier<br/>
    <br/>8.1 Le Vacancier est tenu de fournir des renseignements exacts en ce qui concerne son identité personnelle, y compris son pays de résidence, au sein de son Compte, sur son profil d’utilisateur et dans toute autre communication effectuée sur le Site, y compris dans ses Appréciations sur des Locations de vacances.
    <br/>8.2 Les messages envoyés par l'intermédiaire des systèmes de AtypikHouse doivent uniquement concerner de véritables Demandes d’informations. Nous ne tolérons pas les spams ou les communications électroniques commerciales non sollicitées, de quelque nature que ce soit. Il est interdit d'abuser des systèmes AtypikHouse, tel que par l'envoi de communications commerciales non sollicitées (spam), et de divulguer les données personnelles d’utilisateurs à des tiers sans l'autorisation expresse de l'utilisateur concerné. L’envoi de courriers électroniques et de recommandations du Site via la fonction « Recommander ce site » doit être effectué uniquement avec le consentement du destinataire. Vous vous engagez à protéger toutes données personnelles d’autres utilisateurs avec le même degré de soin que pour vos propres données (en utilisant un standard raisonnable de soin), et vous serez seul(e) responsable en cas d'utilisation abusive, de perte ou de transfert non autorisé de telles données.
    <br/>8.3 Le Vacancier qui a réservé sur le Site a la possibilité de publier sur le Site ses propres appréciations sur la Location de vacances d’un Propriétaire (les « Appréciations du Vacancier »), et le Propriétaire peut consulter les Appréciations du Vacancier et y répondre (la « Réponse du Propriétaire »). Plus de détails concernant les Appréciations du Vacancier et la Réponse du Propriétaire sont disponibles ici. Le Propriétaire a lui aussi la possibilité de publier son appréciation sur le séjour du Vacancier (les « Appréciations du Propriétaire ») et ces Appréciations du Propriétaire peuvent être consultées par tous Propriétaires avec lesquels le Vacancier entre en contact. Les Appréciations du Propriétaire ne peuvent pas être utilisées en vue d’exclure ou de discriminer certaines personnes. L’unique recours, pour le Vacancier, en rapport aux Appréciations du Propriétaire, et la seule et unique obligation de AtypikHouse en rapport aux Appréciations du Propriétaire, consiste à autoriser le Vacancier à publier une Réponse du Vacancier dans un délai de 14 (quatorze) jours à compter de la date de soumission de l’Appréciation du Propriétaire. AtypikHouse décline expressément toute responsabilité quant aux Appréciations du Vacancier et du Propriétaire. Le Vacancier reconnaît et convient que  AtypikHouse pourrait permettre à tous autres Propriétaires avec lesquels le Vacancier est en contact via le Site de consulter les Appréciations du Propriétaire à votre sujet. Plus de détails concernant les Appréciations du Propriétaire sont disponibles ici.
    <br/>8.4 Veuillez prendre note du fait que AtypikHouse ne vérifie ni l'exactitude, ni la véracité des Appréciations du Vacancier, des Réponses du Propriétaire et des Appréciations du Propriétaire et n'a pas la capacité de le faire.
    <br/>8.5 Toutefois, AtypikHouse exige que toutes Appréciations du Vacancier, Réponses du Propriétaire, Appréciations du Propriétaire, et autres communications adressées via le système de AtypikHouse soient conformes aux Recommandations relatives au contenu, et il pourrait refuser de les publier ou les retirer s'il estime qu’elles ne sont pas conformes. AtypikHouse n’éditera pas ni ne modifiera pas les Appréciations pour le compte d’un Vacancier ou d’un Propriétaire. Les Vacanciers et les Propriétaires peuvent contacter le Service Clients en vue de retirer l’Appréciation qu’ils ont publiée. Le Vacancier convient de respecter toutes législations relatives aux exportations et aux embargos. De plus, le Vacancier déclare qu’il ne figure sur aucune liste du gouvernement des États-Unis répertoriant des parties interdites sur le territoire américain, et qu’il a l’âge légal pour conclure des contrats avec AtypikHouse.
    <br/>8.6 AtypikHouse ne procède de manière générale à aucune vérification d’identité. Si le Vacancier suspecte qu’un Propriétaire lui a fourni des informations frauduleuses, il est invité à en aviser AtypikHouse à l’aide du formulaire de contact.
    <br/>8.7 AtypikHouse applique sa Politique de confidentialité. Pour plus d’informations, veuillez consulter la Politique de confidentialité. Le Vacancier consent à ce que ses données soient utilisées de la manière décrite dans la Politique de confidentialité. Les Vacanciers sont informés que de manière générale, les Propriétaires ont généralement autorisé AtypikHouse à publier leurs coordonnées, y compris leurs numéros de téléphone, à l’attention de Vacanciers et à condition que cela soit en rapport avec la réservation d’une Location de vacances. Le Vacancier peut demander à recevoir ces informations sur présentation d’un justificatif de réservation ; autrement, de telles informations peuvent être fournies au Vacancier par le biais de son Compte.
    <br/><br/>9. Indemnisation<br/>
    <br/>Vous convenez de défendre, d’indemniser et de dégager de leur responsabilité le Groupe AtypikHouse et ses actionnaires, dirigeants, administrateurs, salariés et agents respectifs en cas de plaintes, causes d'action, réclamations, recouvrements, pertes, dommages, amendes, pénalités ou autres charges ou frais de tous types et de toute nature, y compris, mais sans s’y limiter, tous frais juridiques et de comptabilité raisonnables facturés ou occasionnés par des tiers en rapport aux éléments suivants, résultant de ceux-ci ou en lien avec ceux-ci : (a) tout contenu ou document que vous soumettez ou fournissez fautivement au Site ; (b) votre utilisation fautive de tout contenu sur le Site ; (c) tout manquement fautif de votre part aux Conditions Générales d’Utilisation Vacanciers ; et (d) votre utilisation fautive de la Location de vacances. AtypikHouse vous notifiera promptement de telles réclamations le cas échéant.
<br/><br/>10. Interdictions<br/>
<br/>Le Vacancier n’est pas autorisé à, directement ou indirectement :
<br/>Exploiter, copier, distribuer, reproduire, modifier, traduire, rendre publiquement accessibles ou décompiler le Site, son contenu, toute base de données intégrée au Site, et tout autre élément similaire, de quelque manière que ce soit, à l’aide d’appareils automatiques ou par le biais de procédures manuelles ;
<br/>Contrôler le contenu du Site ou la plateforme ou les systèmes AtypikHouse à l’aide de robots, spiders ou autres instruments automatiques ; sous réserve, cependant, qu’une exception à ce qui précède soit prévue à la fois en ce qui concerne les moteurs de recherche généralistes sur Internet (à l’exclusion de tout site Internet, moteur de recherche ou autre service proposant des petites annonces ou faisant de la publicité concernant des propriétés à louer, ou tout autre sous-ensemble de ce qui précède ou dont l’activité consiste à fournir d’autres services concurrents à ceux du Site ou de AtypikHouse), et en ce qui concerne tous systèmes d’archivage publics non-commerciales utilisant des outils de collecte d’informations dans le but exclusif d’afficher des liens de connexion au Site, sous réserve, cependant, que chacun d’eux l’effectue à partir d’une adresse IP ou d’une série d’adresses IP stable en utilisant un agent facilement identifiable et compatible avec le fichier robots.txt de AtypikHouse;
<br/>Utiliser le Site, la plateforme, les systèmes de AtypikHouse à des fins autres que celles autorisées par les présentes Conditions Générales d’Utilisation Vacanciers ;
<br/>Utiliser le Site ou les outils et services disponibles sur le Site pour réserver ou solliciter la location d’un bien immobilier autre que celui affiché dans une Annonce valable ;
<br/>Reproduire une quelconque portion du Site sur un autre site Internet ou autrement, à l’aide de quelque procédé que ce soit, notamment, en utilisant un cadre ou une bordure entourant le Site ou en employant toute autre technique d’encadrement permettant d’encercler toute portion ou tout aspect du Site, ou en reproduisant à l’identique ou en dupliquant toute portion du Site ;
<br/>Charger sur le Site ou envoyer sur le Site (ou sur la plateforme ou des systèmes de  AtypikHouse) tous contenus ou programmes qui pourraient endommager les systèmes et le réseau de  AtypikHouse ;
<br/>Publier sur le Site (ou sur la plateforme ou des systèmes de AtypikHouse) un contenu en infraction à une quelconque législation pénale ou à toute autre loi applicable, ou inciter quiconque à commettre une telle infraction ;
<br/>Utiliser ou consulter le Site, la plateforme ou les systèmes de AtypikHouse d’une manière susceptible de nuire à un système ou réseau informatique, y compris en important un virus (le terme « virus » désignant, aux fins des présentes, tout programme délibérément introduit dans un système sans objectif fonctionnel et/ou à des fins destructives, tel que pour afficher un message irritant ou systématiquement remplacer les données résidant sur le disque dur d’un utilisateur) ;
<br/>Afficher ou transmettre des informations qui sont, de quelque manière que ce soit, fausses, frauduleuses ou trompeuses, ou commettre tout acte susceptible d’être considéré comme du hameçonnage (phishing) (qu’il soit primaire, secondaire ou autre) et qui engagerait une responsabilité pénale ou civile ;
<br/>Afficher ou transmettre un quelconque contenu illégal, menaçant, abusif, diffamatoire, diffamant, obscène, vulgaire, indécent, inflammatoire, explicitement sexuel, pornographique ou profane ; 
<br/>Faire référence à AtypikHouse ou à tout membre du Groupe AtypikHouse de quelque façon que ce soit susceptible de faire croire que le Vacancier ou tout site Internet est sponsorisé, affilié, partenaire ou approuvé par AtypikHouse ou tout membre du Groupe AtypikHouse.
<br/><br/>11. Droit de suppression d’un contenu<br/>
<br/>Les Vacanciers sont responsables de s’assurer que leurs communications et les contenus qu'ils publient sur ou en rapport avec le Site, y compris des Appréciations du Vacancier et leurs échanges avec les Propriétaires, ne violent aucune loi ni aucun droit d'aucune personne ou entité et ne contiennent aucune fausse information, aucune insulte, aucune diffamation ni calomnie ni aucune donnée qui violent des droits d’auteur, toute législation sur la protection des données ou nos Recommandations relatives au contenu. AtypikHouse est en droit de vérifier toutes données affichées sur le Site ou sur la plateforme ou les systèmes de AtypikHouse, et de les supprimer ou les modifier lorsque de telles données ne sont plus exactes ou à jour. Sans préjudice de tous autres recours disponibles, AtypikHouse sera en droit de retirer immédiatement toute communication ou tout contenu affiché sur le Site en infraction à ces exigences, ainsi que de suspendre ou d’empêcher l’utilisation d’un quelconque Compte associé.
<br/><br/>12. Notifications<br/>
<br/>12.1 Tous messages à l’attention de notre équipe de support clients AtypikHouse doivent être envoyés à l’aide du formulaire de contact (contact@atypik-house.com), ou par courrier postal à AtypikHouse, 29 rue Napoléon 60350 Pierrefonds. 
<br/>12.2 Tout avis de violation d’un droit d’auteur doit inclure les informations suivantes :
    <br/>Vos adresse, numéro de téléphone et adresse électronique ;
    <br/>Des informations détaillées concernant le contenu en question (reproduction de l’image ou du texte concerné), ainsi qu’un lien direct au Site ;
    <br/>Une déclaration sur l’honneur signée dans laquelle vous affirmez : détenir le droit d’utilisation exclusive du contenu en question ; et que vous n’avez pas autorisé l’usage sous cette forme du contenu en question.                                        
    <br/><br/>13. Responsabilité de AtypikHouse<br/>
    <br/>13.1 Le Site représente simplement un espace pour consulter des Annonces de Locations de vacances référencées sur le Site, de communiquer avec les Propriétaires afin de leur soumettre toutes demandes d’informations ou questions éventuelles, et d’effectuer une réservation auprès d’un Propriétaire afin de louer sa Location de vacances. Nous déclinons toute responsabilité concernant tout contrat que vous signez avec un Propriétaire et toute Location de vacances que vous réservez, sauf en cas d’obligation de collecter des informations fiscales et ou la Taxe de séjour pour le compte du Propriétaire, et nous déclinons toute responsabilité en cas d’actes ou d’omissions de la part de tout Propriétaire ou autre personne(s) ou partie(s) en rapport avec une Location de vacances. Pour toutes les Locations de vacances, votre contrat sera conclu avec le Propriétaire, et ses conditions générales s’appliqueront à vos réservations. Ces conditions générales pourraient limiter et/ou exclure la responsabilité du Propriétaire envers vous, et pour cette raison il vous est conseillé de les lire attentivement avant d’effectuer votre réservation.
    <br/>13.2 Nous ne fournissons aucune protection de responsabilité civile aux Propriétaires, aux Gérants de biens immobiliers et aux Vacanciers, même si un Utilisateur a contracté une assurance auprès de l’un de nos prestataires tiers. Il est recommandé à tout Vacancier de contracter une assurance de voyage adaptée afin de couvrir sa réservation d’une Location de vacances auprès d’un Propriétaire, notamment en cas d’annulation de sa réservation. Il incombe au Vacancier de vérifier que l’assurance qu’il contracte est adéquate et spécifiquement adaptée à ses besoins.
    <br/>13.3 Ni le Groupe AtypikHouse ni aucune filiale ou société affiliée, ni aucun de ses actionnaires, dirigeants, administrateurs, consultants, agents et/ou salariés ni tous autres fournisseurs  tiers d’un outil proposé sur le site d’un membre du Groupe AtypikHouse ne pourront être tenus responsables d’une perte de profits ou de tout autre préjudice, indirect, spécial ou accessoire, ou de tous dommages et intérêts punitifs liés ou résultant du Site, de la plateforme ou des systèmes de AtypikHouse, de tout élément ou contenu que vous envoyez sur le Site ou de l’utilisation du Site par le Vacancier, et/ou de toutes transactions réalisées entre des Utilisateurs, ce même si AtypikHouse a été informé de l’éventualité de tels préjudices. Ces limitations et exclusions ne s’appliquent pas  si les préjudices en question résultent d’une violation des Conditions Générales Vacanciers, d’une négligence ou de tout autre manquement ou violation d’une obligations légale ou règlementaire de la part d’AtypikHouse. Si vous n’êtes pas satisfait(e) du Site (ou de la plateforme ou des systèmes de AtypikHouse), ou si vous êtes en désaccord avec une partie des présentes Conditions Générales d’Utilisation Vacanciers, votre seul et unique recours contre AtypikHouse consiste à cesser d’utiliser le Site. Rien dans les présentes Conditions Générales d’Utilisation Vacanciers ne saurait exclure ni limiter la responsabilité du Groupe AtypikHouse en cas de décès ou de préjudice corporel résultant d’une négligence de sa part, de même qu’en cas de fraude ou de représentation frauduleuse de la part du Groupe AtypikHouse.
    <br/><br/>14. Divers<br/>
    <br/>14.1 Les présentes Conditions Générales d’Utilisation Vacanciers, la Politique de confidentialité et la Notice relative aux cookies constituent l’intégralité de l’accord entre AtypikHouse et le Vacancier concernant leur objet.
    <br/>14.2 AtypikHouse conseille au Vacancier de conserver une copie des présentes Conditions Générales d’Utilisation Vacanciers dans un dossier spécifique sur son ordinateur ou sur papier.
    <br/>14.3 Même si AtypikHouse ne réagit pas en cas de quelconque violation des présentes Conditions Générales d’Utilisation Vacanciers par le Vacancier ou toute autre personne, cela ne signifie pas que AtypikHouse renonce à son droit d’agir en cas de toutes autres violations ultérieures ou similaires.
    <br/>14.4 Les intitulés des différentes clauses des présentes Conditions Générales d’Utilisation Vacanciers ne servent qu’à des fins de référence et ne peuvent en aucun cas affecter l’interprétation ou la construction des présentes Conditions Générales d’Utilisation Vacanciers.
    <br/>14.5 Si une ou plusieurs dispositions des présentes Conditions Générales d’Utilisation Vacanciers est ou sont jugée(s) nulle(s), la validité des autres dispositions n’en sera aucunement affectée.
    <br/>14.6 Si vous résidez en France, vous convenez de ce qui suit :
    <br/>En cas de litige entre Vous et AtypikHouse, Vous avez la possibilité de recourir à une procédure de médiation conventionnelle ou à tout autre mode alternatif de règlement des litiges tels que définis par la loi, et notamment par l’article 1528 du Code de procédure civile français. Le médiateur de consommation dont dépend AtypikHouse est le service du médiateur du e-commerce de la Fédération des Entreprises de Vente à Distance (FEVAD) (http://www.fevad.com/mediation). Après avoir saisi par écrit AtypikHouse, et à défaut de réponse satisfaisante de la part d’AtypikHouse dans un délai de 60 jours, Vous pouvez soumettre Votre litige au médiateur selon les conditions énoncées sur le site internet du médiateur. Vous pouvez contacter le médiateur à l’adresse suivante :
        <br/><br/>Le Service de Médiation du e-commerce
        <br/>60 rue La Boétie – 75008 Paris
        <br/>relationconso@fevad.com
        <br/>http://www.mediateurfevad.fr
        <br/>Alternativement, Vous pouvez aussi soumettre Vos litiges avec AtypikHouse à la plateforme de la Commission européenne relative au règlement en ligne de litiges accessible à http://ec.europa.eu/odr.
    </p>
  </div>
</div>
</main>

@endsection